### PR TITLE
Toolbar position

### PR DESCRIPTION
**Pull request by jbbn**
Set toolbar at `left`, `right` or `bottom`.
`bottom` is the default and exactly like it is today.

The changes in `src/js/template.js` are big ones, but I think it justify the advantages and open new posibilities.
I hope you guys think so too.

Regards!

### CODE REVIEW

**Comment by fengyuanchen** [comment]
Why not just override the CSS style in your app?

For example:

```css
.viewer-toolbar {
  text-align: left; /* or right */
}
```

**Comment by fengyuanchen** [comment]
BTW: The toolbar, navbar and  title are all center-aligned!

**Comment by jbbn** [comment]
Sorry for not providing images of my desirable result.

`text-align` does not solve this. (It's a vertical solution)

screenshot from 2018-01-09 15-36-38
screenshot from 2018-01-09 15-36-23

**Comment by fengyuanchen** [comment]
It is not a common feature, so I will not merge this. I am sorry, and thanks for your PR.

**Comment by jbbn** [comment]
Ok, no problem. Say that it's not a common feature to my design haha.
Well, it really makes sense to me, so I'll maintain this on my fork.
Thanks for your attention. :smiley:

**Pull request closed without merging**
