### PR TITLE
Include randy in more acceptable landscape photos

### PR DESCRIPTION
**Pull request by stephenhandley**

### CODE REVIEW

**Comment by fengyuanchen** [comment]
@stephenhandley Sorry, I have to say your images are not so beautiful as my original images. Please don't pull any requests about images. Thanks!

**Comment by stephenhandley** [comment]
@fengyuanchen I have to disagree as I believe (as do many millions of people) that Randy makes everything more beautiful. but it is ok. I will stop trying to open your eyes to the beauty of Randy.

**Comment by fengyuanchen** [comment]
@stephenhandley I think landscape photographs are more common and acceptable for most of people than a specific people, so I replaced all the pictures of Emma some days ago.

**Comment by stephenhandley** [comment]
Yes, I agree Emma is very very beautiful, but not as beautiful as Randy. I would say, if I were to rank the options: 1) Randy in Tibet very very very beautiful, 2) Randy very very vry beautiful, 3) Emma very very beautiful, 4) Tibet very beautiful. Anyway, that is just my opinion, I may be wrong.

**Pull request closed without merging**
