### PR TITLE
fixed a small bug. converting  name in getData() to hypen-case.

### PR DESCRIPTION
**Pull request by sorskoot**
We ran into an issue with IE10. It turned out the name parameter in the _getData_ function was not used correctly in the last case. This turned into the _getData_ function looking for **'data-originalUrl'** instead of **'data-original-url'** on the _img-tag_. This is fixed by adding a simple function that converts the camelCase string to hyphen-case string.

### CODE REVIEW

**Comment by fengyuanchen** [comment]
Please read the [contributing guidelines](https://github.com/fengyuanchen/viewerjs/blob/master/CONTRIBUTING.md) first before send a pull request. Thanks.

**Comment by sorskoot** [comment]
I'm sorry. I'm not sure what I did wrong. Do you want the dist folder excluded? The changes are made by the build script.

**Comment by fengyuanchen** [comment]
1. Fork the latest repo.
2. Don't change the files in the `dist` directory.

**Comment by sorskoot** [comment]
Hi, I've undone the changes to the dist folder.

**Pull request merged**
