### PR TITLE
fix:to fixed ToolbarOption is undenfined

### PR DESCRIPTION
**Pull request by chenlang0311**
**Summary**

**What kind of change does this PR introduce?** (check at least one)
- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [x]  Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by chenlang0311** [comment]
当项目中使用了TS的时候，打包的时候会报错，错误如图
image

**Comment by fengyuanchen** [comment]
What's your configure for the Viewer class?

**Comment by fengyuanchen** [comment]
What's your configure for the Viewer class?

**Comment by chenlang0311** [comment]
> What's your configure for the Viewer class?

No other options, the options is the defaut, you can see the v-viewer, we are use the package

**Pull request merged**
