### PR TITLE
Add the possibility to edit the toolbar layout

### PR DESCRIPTION
**Pull request by maxime4000**
Add the possibility to edit the toolbar layout so you can choose the button order you want

ex : 
var options = {
"toolbarLayout": ['zoomin', 'zoomout', 'reset', 'prev', 'play', 'onetoone', 'next', 'rotateleft', 'rotateright', 'fliphorizontal', 'flipvertical']
}
var newViewerWithChangedToolBarLayout  = new Viewer(pictures, options);

### CODE REVIEW

**Comment by chamerling** [comment]
This one looks nice!

**Comment by maxime4000** [comment]
Thanks but I don't thinks it will be push in the master branch and I didn't add test due to the fact I wasn't really sure it would be merge.

**Comment by dsdemaria** [comment]
Any word on this possible making it in the final build?

**Comment by maxime4000** [comment]
I would hope to see it in the final build but as a fact, I didn't create unit test like every other components have some. And I did write to the owner of the repo when I was working in the company as a intern but i guess if he has try to reach me, I don't own anymore the email so i never saw it. But if he could reply on why it's not in the final build or if it need fix, it would be interesting to know.

**Pull request closed without merging**
