### PR TITLE
replaceAllImagesWithQuaid

### PR DESCRIPTION
**Pull request by stephenhandley**
replaceallimageswithquaid

### CODE REVIEW

**Comment by tmont** [comment]
I'm not sure about this. Why replace sexy images of one celebrity with sexy pictures of another?

Maybe the sample images should just be different shades of beige so as not to offend anyone of any kind of gender.

Although, certain people might have a beige fetish, so maybe an option to switch the hue might be an easy way to ensure that people who identify as a beige fetishist won't feel like we're singling them out for being weirdos.

Perhaps the best solution is to not show the demo by default, and start with the question "which color is the least sexually attractive to you?" and use that hue for the sample images. However, you'll have to reassure them that you won't be doing anything malicious with such potentially sensitive data.

Maybe the true solution is to re-implement this whole library in pure CSS with no JavaScript whatsoever. That has the polycephalic advantage of:

1. Ensuring users that you won't track their huesexual preferences
2. It'll work offline, so noscript and other JS blockers will still work with this library

Thoughts?

**Comment by fengyuanchen** [comment]
@stephenhandley Thank you for the PR, but I'd like to use my own photographs to avoid license problem.

**Comment by fengyuanchen** [comment]
@tmont Re-implement the Viewer.js by pure CSS?

**Comment by natxty** [comment]
@tmont huesexual

**Comment by stephenhandley** [comment]
@tmont Thank you, I now better understand what the issue is with the previous imagery. I agree that a pure CSS implementation is probably the most reasonable way forward. Hopefully that will be possible.

@fengyuanchen Although I do enjoy the striking images of Tibet that you are now using, it's perhaps worth noting that all images of Randy Quaid are currently in the public domain, as per Bridgeman Art Library v. Corel Corp., 36 F. Supp. 2d 191 (S.D.N.Y. 1999). So, should you ever want to reconsider my PR, I am reasonably certain that legally, at least, you will be on solid ground.

**Comment by fengyuanchen** [comment]
@tmont As this library is built with JavaScript mainly (js: 60KB, css: 8KB), I think it is not possible for me to implement it by pure CSS.

@stephenhandley I think using photos of landscape are more common than a specific person, and will more easy to be accept by most people.

Thank you both!

**Comment by stephenhandley** [comment]
@fengyuanchen I agree, but I think a lot of people find Randy Quaid quite agreeable. For your consideration: https://github.com/stephenhandley/viewerjs/commit/4d68251c405d9b929c194048be6faafcb090b6d7

**Pull request closed without merging**
