### PR TITLE
Add 'index' parameter for 'show' method

### PR DESCRIPTION
**Pull request by ruvor**
Did this for myself. May be someone needs this too.

### CODE REVIEW

**Comment by fengyuanchen** [comment]
Why not just use the `view(index)` method?

**Comment by ruvor** [comment]
Because I needed to show modal viewer initially on some not first picture. And the 'view' method does not trigger modal viewer. It works only when it is already shown.

**Comment by erguotou520** [comment]
I have the same requirement. I want to trigger the `view` method when the modal is invisiable.

**Comment by fengyuanchen** [comment]
Call the show first, and then call the `view` method once the modal shown (use the `shown` event).

**Comment by erguotou520** [comment]
I directly change `index` to some value, and call `show` then.

**Pull request closed without merging**
