### PR TITLE
feat: add download button

### PR DESCRIPTION
**Pull request by wrych**
add a download button that allows to download the currenly viewed image.

**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of the default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome | Google Chrome | 95.0.4638.69 (Official Build) (64-bit)
- [x] Firefox | 94.0 (64-bit)
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [x] Related documents have been updated
- [x] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**
The download button is a feature many sites providing galleries provide. Noteably flickr and facebook enable such features. The feature could be disabled by default, if that is preferred. However, to make it easier for testing I enabled it for now.

I do not have photoshop therefore I could not adapt the .psd file. Sorry for the inconvenience caused.

Furthermore, sorry that I couldn't test the change on more browsers. I suppose if the idea is approvable I could ask around to test on more browsers.

after the change...
after

before the change...
before

### CODE REVIEW

**Comment by fengyuanchen** [comment]
There is already an example of adding a download button: https://fengyuanchen.github.io/viewerjs/examples/custom-toolbar.html

**Comment by fengyuanchen** [comment]
Thanks for your PR, but I think it is not necessary to add a download button into the Viewer.js, as it is not a common feature for most people.

**Comment by wrych** [comment]
Thanks, I completely missed that example. Also, it now appears I misinterpreted the following sentence in the docs:

```
Available keys: "zoomIn", "zoomOut", "oneToOne", "reset", "prev", "play", "next", "rotateLeft", "rotateRight", "flipHorizontal" and "flipVertical".
```

Maybe adding a sentence there that custom buttons might be added could be helpful. 

Anyway, thanks, your response! That information makes me able to fulfill the requirement. Thanks and have a great day.

**Comment by fengyuanchen** [comment]
Okay, I will improve the documentation to avoid misunderstandings.

**Pull request closed without merging**
