### PR TITLE
Video support

### PR DESCRIPTION
**Pull request by plepe**
Add the possibility to include videos in the gallery.

Add a video like this:
```html
        <li><img data-original="../docs/videos/nightsky.mp4" src="../docs/videos/thumbnails/nightsky.png" alt="Nightsky"></li>
```

When viewing the video, it will open the video in an autoplaying video element.

### CODE REVIEW

**Comment by LHC8888** [comment]
did not publish in npm为啥

**Comment by fengyuanchen** [comment]
No plans to support this feature yet as this is just an image viewer currently.

**Comment by Sunny264** [comment]
现在还没支持吗

**Comment by Saqib92** [comment]
this feature can be very helpful..

**Pull request closed without merging**
